modLoader="javafml"

loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="https://github.com/Alchemists-Of-Yore/ClutterNoMore/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://modrinth.com/mod/clutter-no-more"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="moonlight"
    mandatory=true
    versionRange="*"
    ordering="AFTER"
    side="BOTH"